# https://medium.com/@doedotdev/mypy-for-github-action-7da1ebee99e7
on: [push]
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - run: |
        pip install -r requirements.txt -r requirements-dev.txt
    - run: |
        python3 -m mypy --strict porcupine more_plugins/ttk_themes.py
      env:
        MYPYPATH: ./my_stubs
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - run: |
        pip install -r requirements.txt -r requirements-dev.txt
    - run: |
        python3 -m flake8 porcupine tests more_plugins
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - run: |
        pip install -r requirements.txt -r requirements-dev.txt
    - # xvfb is needed for running tkinter
      # not using latest version because https://github.com/GabrielBB/xvfb-action/issues/10
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: |
          python3 -m pytest
  bindcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - run: |
        python3 bindcheck.py porcupine
    - run: |
        python3 bindcheck.py more_plugins
