# https://medium.com/@doedotdev/mypy-for-github-action-7da1ebee99e7
on: [push, pull_request]
jobs:
  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8"]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        pip install -r requirements.txt -r requirements-dev.txt
    - run: |
        git submodule init && git submodule update
    - run: |
        python3 -m mypy --disallow-untyped-defs --show-error-codes --custom-typeshed-dir=typeshed porcupine more_plugins
      env:
        MYPYPATH: ./my_stubs
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8"]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        pip install -r requirements.txt -r requirements-dev.txt
    - # xvfb is needed for running tkinter
      uses: GabrielBB/xvfb-action@v1.4
      with:
        run: |
          python3 -m pytest
  pycodestyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - run: |
        pip install -r requirements.txt -r requirements-dev.txt
    - run: |
        python3 -m pycodestyle porcupine tests more_plugins
  pyflakes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - run: |
        pip install -r requirements.txt -r requirements-dev.txt
    - run: |
        python3 -m pyflakes porcupine tests more_plugins
  bindcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - run: |
        python3 bindcheck.py porcupine
    - run: |
        python3 bindcheck.py more_plugins
